'''
Encoder Inputs
- Vector Reprentation of the SMILE, generated by ChemBERTa
- Condition/Initial state vector
Encoder Output
- Latent Vector

Decoder Inputs
- Latent Vector
- Condition/Initial state vector

Decoder Output
- Image Vector Reprentation of the SMILE to be converted into image

'''

import sys, os
import numpy as np

import tensorflow as tf
from tensorflow.Keras import layers,regularizers


class VAE(tf.keras.Model):
    def __init__(self):
        pass

    def build_encoder(self):
        pass

    def build_decoder(self):
        pass

    def sampling(self):
        pass

    def call(self):
        pass

    def compute_loss(self):
        pass

